# Site settings
title: SimpleAPI.io
email: contact-us@simpleapi.io
description: > # this means to ignore newlines until "baseurl:"
  Keep it simple stupid
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.simpleapi.io" # the base hostname & protocol for your site
twitter_username: simple_api
github_username:  simpleapi-io
appurl: "http://simpleapi.io" # the base hostname & protocol for your site

# Build settings
kramdown:
  input: GFM
  coderay_line_numbers: nil

collections:
  docs:
    output: true
